// Builds the Thai interface dictionary for the website.
//
//   node scripts/build_i18n.mjs            # writes static/i18n/th.js and static/i18n/th.js.gz
//   node scripts/build_i18n.mjs --check    # also fails if an API message has no Thai entry
//
// Sources: i18n/th.json (strings carried over from 3.x), every i18n/th/*.json feature file (later
// files win) and finally i18n/th/*.overrides.json, the reviewed corrections. Keys are the English
// interface strings exactly as written in templates/ and static/js/; a key may be a template with
// {placeholders}. static/js/i18n.js loads the result.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { compile, protectThai, strip } from "./thai-keep.mjs";

const root = new URL("../", import.meta.url);
const dir = new URL("i18n/", root);
const merged = JSON.parse(readFileSync(new URL("th.json", dir), "utf8"));
const seen = new Map(Object.keys(merged).map((k) => [k, "th.json"]));
// Feature files in name order, then the reviewed corrections (*.overrides.json), which always win.
const isOverride = (f) => f.endsWith(".overrides.json");
const files = readdirSync(new URL("th/", dir)).filter((f) => f.endsWith(".json")).sort();
for (const name of [...files.filter((f) => !isOverride(f)), ...files.filter(isOverride)]) {
  const data = JSON.parse(readFileSync(new URL("th/" + name, dir), "utf8"));
  for (const [k, v] of Object.entries(data)) {
    if (typeof v !== "string") throw new Error(`${name}: value for "${k}" must be a string`);
    if (seen.has(k) && merged[k] !== v && process.env.I18N_VERBOSE) console.warn(`override "${k}" (${seen.get(k)} -> ${name})`);
    merged[k] = v;
    seen.set(k, name);
  }
}

// Every user-facing API message (scripts/i18n_api_messages.py lists them) needs a Thai entry,
// either exact or through a {placeholder} template.
if (process.argv.includes("--check")) {
  const api = JSON.parse(readFileSync(new URL("api-messages.en.json", dir), "utf8")).messages;
  const templates = Object.keys(merged).filter((k) => k.includes("{")).map((k) => new RegExp("^" + k.replace(/[.*+?^$()|[\]\\]/g, "\\$&").replace(/\\?\{[^}]+\\?\}/g, ".+") + "$"));
  const missing = api.filter((m) => !(m in merged) && !templates.some((t) => t.test(m)));
  if (missing.length) {
    console.error(`i18n: ${missing.length} API messages have no Thai entry:\n  ` + missing.join("\n  "));
    process.exit(1);
  }
}

// Thai line breaking (ICU) splits words it does not know mid-word ("แพ็ก|เกจ", "แช|ตนั้|นพ|ร้|อม").
// scripts/thai-keep.mjs keeps the reviewed words in i18n/th-keep-together.json on one line (U+2060)
// and separates them from neighbouring Thai letters (U+200B) so the following words segment correctly.
const keep = compile(JSON.parse(readFileSync(new URL("th-keep-together.json", dir), "utf8")).words);
let protectedCount = 0;
for (const [k, v] of Object.entries(merged)) {
  const out = protectThai(v, keep);
  if (out !== strip(v)) protectedCount++;
  merged[k] = out;
}
const thJs = "/* Generated by scripts/build_i18n.mjs from i18n/; do not edit. */\nwindow.LC_TH=" + JSON.stringify(merged) + ";\n";
writeFileSync(new URL("static/i18n/th.js", root), thJs);
// Pre-compressed copy served by main.py to browsers that accept gzip (mtime 0: reproducible bytes).
writeFileSync(new URL("static/i18n/th.js.gz", root), gzipSync(Buffer.from(thJs, "utf8"), { level: 9 }));
console.log(`i18n: ${Object.keys(merged).length} Thai strings (${protectedCount} with words kept together)`);
