"""Build the Thai coursework report from retained content and the selected template.

Use Python with python-docx and lxml. --page-map is generated by report_page_map.py
after rendering. Cached TOC/TOF pages are updated without destroying real fields.
No zero-width spaces or forced mid-word line breaks are inserted.
"""
from pathlib import Path
from io import BytesIO
from copy import deepcopy
import argparse, json, re, sys, tempfile
from docx import Document
from docx.shared import Pt, Twips, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_TAB_ALIGNMENT
from docx.enum.section import WD_SECTION_START
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.text.paragraph import Paragraph
from docx.table import Table

ROOT=Path(__file__).resolve().parents[1]
TEMPLATE=ROOT/'docs/report/template'
sys.path.insert(0,str(TEMPLATE/'scripts'))
from new_report import create
from apply_toc_format import apply_parts as apply_toc
from apply_text_layout import apply_parts as apply_layout
from zipfile import ZipFile,ZIP_DEFLATED

FONT='TH Sarabun New'
TITLE='LabClear แชทบอทบริการตรวจสุขภาพ'
def clean(text):return text.replace('\u200b','').replace('\ufeff','')
def tag(name,**attrs):
 e=OxmlElement('w:'+name)
 for k,v in attrs.items():e.set(qn('w:'+k),str(v))
 return e
def font(r,size=16,bold=False,italic=False):
 r.font.all_caps=False;r.font.small_caps=False;r.font.color.rgb=RGBColor(0,0,0);r.font.name=FONT;r.font.size=Pt(size);r.bold=bold;r.italic=italic
 pr=r._r.get_or_add_rPr();rf=pr.find(qn('w:rFonts'))
 for key in ['ascii','hAnsi','cs','eastAsia']:rf.set(qn('w:'+key),FONT)
 pr.append(tag('szCs',val=size*2));pr.append(tag('lang',val='th-TH',eastAsia='th-TH',bidi='th-TH'))
def field(p,instruction,cached='1'):
 r=p.add_run();font(r);r._r.append(tag('fldChar',fldCharType='begin'))
 code=OxmlElement('w:instrText');code.set(qn('xml:space'),'preserve');code.text=' '+instruction+' ';r._r.append(code)
 r._r.append(tag('fldChar',fldCharType='separate'));font(p.add_run(str(cached)))
 r=p.add_run();font(r);r._r.append(tag('fldChar',fldCharType='end'))
def geometry(section,landscape=False):
 g=json.loads((TEMPLATE/'references/geometry.json').read_text())[1 if landscape else 0]
 section.page_width=Twips(int(g['pgSz']['w']));section.page_height=Twips(int(g['pgSz']['h']))
 for k in ['top','bottom','left','right']:setattr(section,k+'_margin',Twips(int(g['pgMar'][k])))
 section.header_distance=Twips(720);section.footer_distance=Twips(int(g['pgMar']['footer']))
 section.gutter=Twips(0)
def page_number(section,fmt='decimal',start=None):
 sp=section._sectPr
 for e in list(sp.findall(qn('w:pgNumType'))):sp.remove(e)
 n=tag('pgNumType',fmt=fmt)
 if start is not None:n.set(qn('w:start'),str(start))
 sp.append(n)
def footer(section,fmt='decimal',start=None,blank=False):
 section.header.is_linked_to_previous=False;section.footer.is_linked_to_previous=False
 for part in [section.header,section.footer]:
  for e in list(part._element):part._element.remove(e)
 p=section.footer.add_paragraph();p.style='Footer'
 if not blank:
  p.paragraph_format.tab_stops.clear_all();p.paragraph_format.space_after=Pt(6);p.paragraph_format.tab_stops.add_tab_stop(section.page_width-section.left_margin-section.right_margin,WD_TAB_ALIGNMENT.RIGHT)
  borders=tag('pBdr');borders.append(tag('top',val='thickThinSmallGap',sz='12',space='1',color='000000'));p._p.get_or_add_pPr().append(borders)
  font(p.add_run(TITLE+'\t'),12,italic=True);field(p,'PAGE','1')
  for r in p.runs:font(r,12,italic=True)
 page_number(section,fmt,start)
def bodyp(d,text,style='Normal'):
 p=d.add_paragraph(style=style);font(p.add_run(clean(text)),18 if style=='Heading 1' else 16,style.startswith('Heading'))
 p.paragraph_format.space_before=Pt(6);p.paragraph_format.space_after=Pt(6);p.paragraph_format.line_spacing=1
 p.paragraph_format.first_line_indent=Twips(540) if style=='Normal' else None
 p.alignment=WD_ALIGN_PARAGRAPH.CENTER if style=='Heading 1' else WD_ALIGN_PARAGRAPH.LEFT
 if style.startswith('Heading'):p.paragraph_format.keep_with_next=True
 return p

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--out',default=str(ROOT/'docs/report/LabClear_Report_TH.docx'));ap.add_argument('--page-map');args=ap.parse_args()
 pages=json.loads(Path(args.page_map).read_text()) if args.page_map else {}
 source=Document(ROOT/'docs/report/source/LabClear_Report_TH_source.docx')
 with tempfile.TemporaryDirectory() as tmp:
  seed=Path(tmp)/'seed.docx';create(seed,True);d=Document(seed)
  for e in list(d._element.body):
   if e.tag!=qn('w:sectPr'):d._element.body.remove(e)
  # Retain the selected template's styles, but only G1/G2 sections are needed.
  geometry(d.sections[0]);footer(d.sections[0],blank=True)
  d.sections[0].different_first_page_header_footer=False
  for name in ['Normal','Heading 1','Heading 2','Heading 3','Caption','Table of Figures']:
   try:s=d.styles[name]
   except KeyError:continue
   s.font.name=FONT;s.font.size=Pt(18 if name=='Heading 1' else 16)
  d.styles['Footer'].paragraph_format.tab_stops.clear_all()
  # Cover: use the actual project logo already in the supplied report.
  logo=next((e for e in source._element.body.iter() if e.tag==qn('a:blip')),None)
  if logo is not None:
   p=d.add_paragraph(style='Title');p.alignment=1;p.add_run().add_picture(BytesIO(source.part.related_parts[logo.get(qn('r:embed'))].blob),width=Inches(1.5))
  for text,size,bold in [('รายงานโครงงาน',22,True),(TITLE,20,True),('แนะนำแพ็กเกจและช่วยอ่านใบผลตรวจจากข้อมูลอ้างอิง',18,False),('รายวิชา 06048308 Intelligent Chatbot Development',16,False),('68076055 นายวัชรินทร์ บัวสอน',16,False),('68076060 นายศิริพล ศรีเฮงไพบูลย์',16,False),('ตุลาคม 2569',16,False),('ฉบับส่งมอบซอฟต์แวร์และรายงาน 3.0.1',16,True),('ผลโมเดลจริงรอบ 2 และผลตรวจซอฟต์แวร์ของ candidate',16,False)]:
   p=d.add_paragraph(style='Title');p.alignment=1;p.paragraph_format.space_before=Pt(16);font(p.add_run(text),size,bold)
  for text in ['https://github.com/siriponsri/LabClear','https://labclear.onrender.com']:
   p=d.add_paragraph(style='Title');p.alignment=1;font(p.add_run(text),14)
  sec=d.add_section(WD_SECTION_START.NEW_PAGE);geometry(sec);footer(sec,'lowerRoman',1)
  # Gather outline/captions from source, after its old TOC.
  blocks=[];active=False;table_idx=-1
  for el in source._element.body:
   if el.tag==qn('w:p'):
    p=Paragraph(el,source);text=clean(p.text)
    if text=='บทสรุป' and '\t' not in text:active=True
    if active:blocks.append(('p',p))
   elif el.tag==qn('w:tbl'):
    table_idx+=1
    if active:blocks.append(('t',(table_idx,Table(el,source))))
  heads=[];figs=[];tables=[]
  for kind,obj in blocks:
   if kind!='p':continue
   t=clean(obj.text)
   if (obj.style.name if obj.style else '').lower().startswith('heading') or t in ['บทสรุป'] or t.startswith('ภาคผนวก'):
    level=2 if re.match(r'^\d+\.\d+',t) else 1;heads.append((t,level))
   if re.match(r'^ภาพที่ \d+',t):figs.append(t)
   if re.match(r'^ตารางที่ \d+',t):tables.append(t)
  # New appendix adds a reviewable handover and demo script.
  heads.append(('ภาคผนวก ค การส่งมอบและสาธิต',1))
  lists=[('สารบัญ','TOC \\o "1-3" \\h \\z \\w',heads),('สารบัญภาพ','TOC \\h \\z \\c "ภาพที่"',[(t,0) for t in figs]),('สารบัญตาราง','TOC \\h \\z \\c "ตารางที่"',[(t,0) for t in tables])]
  for j,(title,code,items) in enumerate(lists):
   if j:d.add_page_break()
   p=bodyp(d,title);p.alignment=1;p.paragraph_format.first_line_indent=Twips(0)
   for r in p.runs:font(r,18,True)
   p=bodyp(d,'หน้า');p.alignment=2;p.paragraph_format.first_line_indent=Twips(0)
   for i,(text,level) in enumerate(items):
    p=d.add_paragraph(style=d.styles['TOC'+str(level)] if level else d.styles['TableofFigures'])
    if i==0:
     r=p.add_run();r._r.append(tag('fldChar',fldCharType='begin'));c=OxmlElement('w:instrText');c.text=' '+code+' ';r._r.append(c);r._r.append(tag('fldChar',fldCharType='separate'))
    font(p.add_run(text+'\t'+str(pages.get(text,'1'))))
    if i==len(items)-1:p.add_run()._r.append(tag('fldChar',fldCharType='end'))
  sec=d.add_section(WD_SECTION_START.NEW_PAGE);geometry(sec);footer(sec,'decimal',1)
  landscape=False
  pending_caption=None
  def orient(want):
   nonlocal landscape
   if want!=landscape:
    s=d.add_section(WD_SECTION_START.NEW_PAGE);geometry(s,want);footer(s);landscape=want
  def caption(text):
   m=re.match(r'^(ภาพที่|ตารางที่) (\d+)\s*(.*)',text)
   p=d.add_paragraph(style='Caption');p.alignment=1 if m[1]=='ภาพที่' else 0;p.paragraph_format.keep_with_next=m[1]=='ตารางที่'
   font(p.add_run(m[1]+' '));field(p,'SEQ '+m[1]+' \\* ARABIC',m[2]);font(p.add_run(' '+m[3]))
  for kind,obj in blocks:
   if kind=='p':
    p=obj;t=clean(p.text)
    if re.match(r'^ตารางที่ \d+',t):pending_caption=t;continue
    if not t and not p._p.findall('.//'+qn('a:blip')):continue
    if t.startswith('ภาคผนวก ข'):
     orient(False)
    ishead=(p.style.name if p.style else '').lower().startswith('heading') or t=='บทสรุป' or t.startswith('ภาคผนวก')
    if ishead:
     level=2 if re.match(r'^\d+\.\d+',t) else 1
     if level==1:orient(False)
     np=bodyp(d,t,'Heading '+str(level))
     if level==1 and t!='บทสรุป':np.paragraph_format.page_break_before=True
     continue
    if re.match(r'^ภาพที่ \d+',t):caption(t);continue
    images=p._p.findall('.//'+qn('a:blip'))
    if images:
     np=d.add_paragraph(style='Caption');np.alignment=1;np.paragraph_format.keep_with_next=True
     for blip in images:
      part=source.part.related_parts[blip.get(qn('r:embed'))]
      # Scale wide diagrams to the available width, never crop content.
      np.add_run().add_picture(BytesIO(part.blob),width=Inches(8.6 if landscape else 6.1))
     continue
    if t.startswith('ผล pytest 170'):
     t='candidate 3.0.1 ผ่าน pytest 205 กรณีในสภาพแวดล้อม Python 3.12 โดยไม่เรียกผู้ให้บริการจริง ผล Playwright และรายละเอียดอยู่ใน docs/evidence/release/ ส่วนผลโมเดลจริงในหัวข้อ 7.2–7.4 ยังคงเป็นรอบ 2 ก่อนแก้ ไม่ถือเป็นผลรอบใหม่ของ candidate'
    if t.startswith('การแก้ช่วงอ้างอิงเห็นผล'):
     t+=' candidate รอบนี้แก้ให้มีข้อความค่าวิกฤตมาตรฐานโดยไม่ถูกประโยคเงื่อนไขกลบ ตรวจช่วงค่าที่ผูกกับชื่อรายการและชนิดแหล่งอ้างอิงก่อนส่งให้ reviewer และเพิ่มการแก้แถว OCR ที่ตกหล่นในหน้าตรวจทานแล้ว ผลจริงหลัง deploy ยังรอการทดสอบรอบ 3'
    if t.startswith('ผลดิบ course_eval_results.json'):
     t+=' พบข้อจำกัดของตัวให้คะแนนเดิมที่ลบเครื่องหมายจุดทศนิยมและใช้ชื่อรายการบางส่วน จึงแก้ scorer รุ่น 2 สำหรับการรันถัดไป ผลคะแนนรอบ 2 ในเล่มเป็นข้อมูลประวัติ ไม่คำนวณย้อนหลังใหม่เพราะไม่มีแถว OCR ครบทุกคอลัมน์ในไฟล์เดิม'
    bodyp(d,t)
   else:
    idx,old=obj;wide=len(old.columns)>=5;orient(wide)
    if pending_caption:caption(pending_caption);pending_caption=None
    tb=d.add_table(rows=0, cols=len(old.columns));tb.alignment=WD_TABLE_ALIGNMENT.CENTER;tb.autofit=False
    width=d.sections[-1].page_width-d.sections[-1].left_margin-d.sections[-1].right_margin
    oldwidth=[c.width or Inches(1) for c in old.columns];factor=width/sum(oldwidth)
    for col,w in zip(tb.columns,oldwidth):col.width=int(w*factor)
    for ri,row in enumerate(old.rows):
     cells=tb.add_row().cells
     tb.rows[-1]._tr.get_or_add_trPr().append(tag('cantSplit'))
     if ri==0:tb.rows[-1]._tr.get_or_add_trPr().append(tag('tblHeader'))
     for ci,(c,oc) in enumerate(zip(cells,row.cells)):
      c.width=tb.columns[ci].width;c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.TOP
      text=clean(oc.text)
      if text.startswith(('01_A_', '02_A_', '03_B_', '04_B_', '05_C_')):text=text.replace('_',' ')
      if idx==24 and ri>0 and ci==2:text='ผ่าน 205 กรณี' if ri==1 else 'ผ่าน 34/34 กรณี (ใช้ model doubles)'
      if idx==24 and ri==1 and ci==0:text='pytest 205 กรณี'
      if idx==1 and ri==4 and ci==1:text='205/205'
      if idx==1 and ri==5 and ci==2:text='ทดสอบ candidate รอบนี้ ใช้ model doubles'
      if idx==1 and ri==4 and ci==2:text='ทดสอบ candidate รอบนี้ ไม่มี provider calls'
      pr=c._tc.get_or_add_tcPr();b=tag('tcBorders')
      for edge in ['top','left','bottom','right']:b.append(tag(edge,val='single',sz='4',color='000000'))
      pr.append(b)
      if ri==0:pr.append(tag('shd',fill='E7E6E6'))
      for pi,line in enumerate(text.split('\n')):
       cp=c.paragraphs[0] if pi==0 else c.add_paragraph();cp.style='Normal';cp.alignment=1 if ri==0 else 0
       cp.paragraph_format.first_line_indent=Twips(0);cp.paragraph_format.space_before=Pt(0);cp.paragraph_format.space_after=Pt(6);cp.paragraph_format.line_spacing=1
       font(cp.add_run(line),16,ri==0)
  orient(False)
  p=bodyp(d,'ภาคผนวก ค การส่งมอบและสาธิต','Heading 1');p.paragraph_format.page_break_before=True
  for t in ['ชุดส่งมอบประกอบด้วย git bundle รายงาน Word และ PDF บันทึกผลทดสอบอัตโนมัติ ผลดิบรอบ 2 และคำสั่ง PowerShell สำหรับนำเข้า ตรวจ และ push โดยเจ้าของ repo',
            'ก่อนส่งรายวิชา ให้รอ Render deploy commit ที่นำเข้าจาก bundle แล้วรัน scripts/course_eval.py ด้วย --expected-commit เพื่อป้องกันการทดสอบผิดรุ่น การรันนี้ใช้ API จริงและอยู่ภายใต้เพดานที่ตั้งไว้ ต้องตรวจผลรอบ 3 ก่อนกล่าวว่าบั๊กด้านคุณภาพคำตอบปิดครบ',
            'การตรวจเอกสารใช้ LibreOffice render และตรวจทุกหน้าในสภาพแวดล้อมจัดทำ ยังไม่ได้ตรวจด้วย Microsoft Word บนเครื่องเจ้าของ ใช้ scripts/Finalize-Report.ps1 เพื่ออัปเดตฟิลด์และส่งออก PDF จาก Word แล้วตรวจการตัดคำและเลขหน้าอีกครั้ง โดยสคริปต์ไม่เปิด macro หรือแก้ Word Options',
            'แผนคลิปไม่เกิน 3 นาที: 0:00–0:20 แนะนำชื่อโครงงานและผู้พัฒนา 0:20–0:45 แสดงธุรกิจและข้อมูลจำลอง 0:45–1:20 ถามแพ็กเกจและคำถาม RAG 1:20–2:10 ส่งภาพ ตรวจแก้ค่าและยืนยัน 2:10–2:35 สาธิตการปฏิเสธคำขอที่ไม่เหมาะสม 2:35–3:00 แสดงผลทดสอบ ข้อจำกัด และซอร์สโค้ด',
            'ต้นแบบยังไม่ใช่บริการทางการแพทย์จริง Google OAuth กับฐานข้อมูล PostgreSQL บน Render และผู้ให้บริการโมเดลจริงต้องตรวจในสภาพแวดล้อมที่เจ้าของตั้งค่า รายงานนี้ไม่อ้างผลการตรวจที่ยังไม่ได้รัน']:
   bodyp(d,t)
  out=Path(args.out);out.parent.mkdir(parents=True,exist_ok=True);d.save(out)
  with ZipFile(out) as z:parts={n:z.read(n) for n in z.namelist()}
  apply_toc(parts);apply_layout(parts)
  with ZipFile(out,'w',ZIP_DEFLATED) as z:
   for n,data in parts.items():z.writestr(n,data)
  print(out)

if __name__=='__main__':main()
