"""List the English messages the API can show to a person, for the website's Thai dictionary.

The backend answers in English (``ConversationError`` messages and ``"message"`` fields); the website
translates them in the browser with static/i18n/th.js. This script finds those strings in the Python
sources with ``ast`` (f-strings become ``{placeholder}`` templates) and writes
i18n/api-messages.en.json. ``node scripts/build_i18n.mjs --check`` then fails when one has no Thai
translation.

    python scripts/i18n_api_messages.py           # print a summary, exit 1 if the file is stale
    python scripts/i18n_api_messages.py --write   # regenerate the list
"""
from __future__ import annotations

import ast
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "i18n/api-messages.en.json"
SOURCES = sorted([ROOT / "main.py", *(ROOT / "routers").glob("*.py"), *(ROOT / "services").glob("*.py")])
# Operator/configuration diagnostics never reach a customer page, but the staff desk shows them, so
# they are listed too. Internal exception text that only goes to logs is not an API message.


def _name(node: ast.AST) -> str:
    """A readable placeholder name for an f-string expression."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Subscript):
        key = node.slice
        if isinstance(key, ast.Constant) and isinstance(key.value, str):
            return key.value
        return _name(node.value)
    if isinstance(node, ast.Call):
        if isinstance(node.func, ast.Attribute) and node.func.attr == "join" and node.args:
            return _name(node.args[0])
        if node.args:
            return _name(node.args[0])
        return _name(node.func)
    return "value"


def _text(node: ast.AST) -> str | None:
    """A string constant, an f-string as a template, or an implicit concatenation of both."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        out = []
        for part in node.values:
            if isinstance(part, ast.Constant):
                out.append(str(part.value))
            elif isinstance(part, ast.FormattedValue):
                out.append("{" + _name(part.value) + "}")
        return "".join(out)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _text(node.left), _text(node.right)
        if left is not None and right is not None:
            return left + right
    return None


def _person_facing(text: str) -> bool:
    # A sentence with letters; not a code, a key or a format pattern.
    return bool(re.search(r"[A-Za-z]{2,}\s+[A-Za-z]", text)) and not text.startswith(("http", "/api"))


def collect() -> dict[str, list[str]]:
    found: dict[str, set[str]] = {}

    def add(text: str | None, where: str):
        if text and _person_facing(text):
            text = re.sub(r"\{(\w+)\}(\[:\d+\])?", r"{\1}", text).strip()
            found.setdefault(text, set()).add(where)

    for path in SOURCES:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                fn = node.func
                name = fn.id if isinstance(fn, ast.Name) else fn.attr if isinstance(fn, ast.Attribute) else ""
                if name == "ConversationError" and len(node.args) >= 2:
                    add(_text(node.args[1]), rel)
            elif isinstance(node, ast.Dict):
                for key, value in zip(node.keys, node.values):
                    if isinstance(key, ast.Constant) and key.value == "message":
                        add(_text(value), rel)
    return {k: sorted(v) for k, v in sorted(found.items())}


def main() -> int:
    messages = collect()
    payload = {"_about": "Generated by scripts/i18n_api_messages.py from the API sources. Each English message needs a Thai entry in i18n/th/*.json (exact text, or a {placeholder} template).",
               "messages": list(messages)}
    text = json.dumps(payload, ensure_ascii=False, indent=1) + "\n"
    if "--write" in sys.argv:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {len(messages)} messages to {OUT.relative_to(ROOT).as_posix()}")
        return 0
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    print(f"{len(messages)} API messages; committed list {'up to date' if current == text else 'STALE (run with --write)'}")
    return 0 if current == text else 1


if __name__ == "__main__":
    raise SystemExit(main())
