/*
 * Cloudflare entry for the LabClear website.
 *
 * One public origin serves both the pages and the API, so the session cookie, CSRF header and
 * the API's Origin check work exactly as in local development:
 *   /api/*, /health  -> API worker (service binding "API": FastAPI in a Cloudflare Container)
 *   everything else  -> Next.js (OpenNext)
 */
// @ts-ignore - generated by `opennextjs-cloudflare build`
import { default as nextHandler } from "./.open-next/worker.js";

interface Env {
  API?: { fetch: (request: Request) => Promise<Response> };
  API_ORIGIN?: string;
  [key: string]: unknown;
}

const isApi = (path: string) => path === "/health" || path.startsWith("/api/");

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (isApi(url.pathname)) {
      // Local preview (`npm run cf:preview`): API_ORIGIN points at a FastAPI on this machine.
      if (env.API_ORIGIN) {
        const target = new URL(url.pathname + url.search, env.API_ORIGIN);
        const headers = new Headers(request.headers);
        headers.set("X-Forwarded-Host", url.host);
        return fetch(new Request(target, { method: request.method, headers, body: request.body, redirect: "manual" }));
      }
      if (env.API) return env.API.fetch(request);
      return Response.json({ code: "api_unavailable", message: "The LabClear API is not connected." }, { status: 503 });
    }
    return nextHandler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

// @ts-ignore - Durable Object classes generated by OpenNext (unused but exported for completeness)
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
